### ISSUE TITLE
License for Repo

### ISSUE THREAD

**Issue by cg-dv** [lakindu2002/pulumi-aws-pdf-generator#1]
Hello Lakindu,

Thank you for writing the public blog post [Building a PDF Generator using AWS Lambda](https://dev.to/aws-builders/building-a-pdf-generator-using-aws-lambda-4220).

I am writing a PDF generator and read your blog post as reference material.  I was considering using the code (either partially or refactored for my own needs).

I noticed that your code is on GitHub, but there is no license information for the repository.  Would you be able to add the license to the repository (in a LICENSE.txt file, LICENSE.md file and/or in the README.md)?  If you want others to be able to use it (MIT License, etc.), the sites below might be helpful in choosing a license:

[choosealicense.com](https://choosealicense.com/)
[Creative Commons](https://creativecommons.org/about/program-areas/software/)

If you do not want others to use the code, that is understandable, but due to its public availability in the blog post and on your GitHub page I thought you might be interested in an open source license for this project.

Thank you for your help,
Chris

**Comment by lakindu2002** [comment]
I've added the license @cg-dv
